name: realdex_pour

task_name: pour

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    agent_pos:
      shape: [7]
      type: low_dimx
  action:
    shape: [7]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.realdex_dataset.RealDexDataset
  zarr_path: /DATA/disk0/lpy/baseline/3D-Diffusion-Policy/3D-Diffusion-Policy/data/dp3_real/real_robot_demo/pour_40demo_1024.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
